= Git and Githook
Ayman Patel
:toc:
:toclevels: 4
:icons: font

> Repo to learn Git and Githook

== Git 

=== Sync forked repository from upstream

link:git/sync-fork.adoc[Doc link]

=== `gitattributes`


==== Code example

`gitattributes`:

```
# Auto detect text files and perform LF normalization
* text=auto

# Do not use auto for everything `https://stackoverflow.com/a/38017715/9642851` The above line is overrided in subsequent lines
*.txt text
*.html text
*.css text
*.js text
```

NOTE: If `gitattributes` is not added in first commit, you need to do the following from this https://stackoverflow.com/a/40031549/9642851[link]

== Githooks

**Type of githooks**

    - prehooks
    - prepush
    - etc
    
=== Java Gradle (`pre-commit`)

Running `./gradlew clean test` in `.git/hooks/pre-commit`

=== Python (`commit-msg`)

https://www.youtube.com/watch?v=EvpZkdkp-v0[Youtube Link]


NOTE: Symbolic link between `python/commit-msg.py` and `.git/hooks/commit-msg`


==== Windows
`.\install_hooks.bat` : Run this on Windows to create symbolic Link


==== UNIX/Linux

WARNING: The githooks does not work in Ubuntu. Works on Windows though.

`./install_hooks.sh` : Run this on Mac/Linux to create symbolic Link

1. Git hooks are ignored by default
    - hint: The '.git/hooks/commit-msg' hook was ignored because it's not set as executable.
    - hint: You can disable this warning with `git config advice.ignoredHook false`.

2. Remember to do `chmod 777 install_hooks.sh` before `sudo ./install_hooks.sh`



=== Node

npm has a package https://www.npmjs.com/package/husky[husky] for Git hooks.

Prettier (checkstyle but for node) has npm package (https://prettier.io/docs/en/precommit.html[pretty-quick]) for use in Husky's pre-commit config.

== Topics to explore

=== How to use `checkstyle` in pre-commit
NOTE: It is harder on researching on google.
 
== Operatin System

link:operating-system/README.adoc[Link]

== POSIX

link:posix/README.adoc[Link]



